[Add] footer, popUpUser and auth0 implementation
LeonardoIrusta01/Oasis-Front pull request #32
Opened 2023-06-29 00:05 UTC by LucianoFedericoC

2023-06-29 03:01 UTC, tomas2204 requested changes

2023-06-29 03:01 UTC, tomas2204 commented on src/components/sideBar/sideBar.tsx
> +		console.log("hola")
borra los console log

2023-06-29 03:01 UTC, tomas2204 commented on src/components/sideBar/sideBar.tsx
> +		console.log(res)
borrar console log

2023-06-29 03:01 UTC, tomas2204 commented on src/app/layout.tsx
> +console.log(domain, client_id);
borrar console log

2023-06-29 03:01 UTC, tomas2204 commented on src/components/cardDetail/index.tsx
>  						<svg
Llevarse el SVG a un archivo aparte del codigo HTML para poder diferenciar el contenido del Icono, del contenido del componente.

2023-06-29 03:01 UTC, tomas2204 commented on src/components/cardDetail/index.tsx
>  										fill='#000000'>
Mismo caso, llevarse el SVG a un archivo externo

2023-06-29 03:01 UTC, tomas2204 commented on src/components/cardDetail/index.tsx
>  										transform='rotate(0)'>
Mismo caso, llevarse el SVG a un archivo externo al principal.

2023-06-29 03:01 UTC, tomas2204 commented on src/components/productCard/index.tsx
> +							clipRule='evenodd'
Verifica que estas propiedades de los SVG y sus Path no esten perjudicando el Performance ya que yo estuve corrigiendo muchos de los que pusiste porque lo tomaba mal el navegador.

2023-06-29 03:01 UTC, tomas2204 commented on src/components/signUp/index.tsx
> +      window.location.replace("/login")
no usar metodo Replace, usar metodo window.location.assign, ya que al utilizar este metodo hacemos que el usuario pierda el historial de la navegacion, por lo que no le reconoce la ruta al volver para atras.

2023-06-29 03:01 UTC, tomas2204 commented on src/components/signUp/index.tsx
>                    {showPass ? <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" height={"1.5rem"}>
Llevar SVG a un archivo externo del componente.

2023-06-29 03:01 UTC, tomas2204 commented on src/redux/services/usersApi.ts
> +interface apiLoginResponse {
Llevarse todas las interfaces a un archivo de interface.ts, para centralizar todas las definiciones.

2023-06-30 02:52 UTC, tomas2204 approved these changes, later dismissed

2023-07-01 05:30 UTC, TomyAvila00 approved these changes

2023-07-01 09:09 UTC, tomas2204 approved these changes

2023-07-01 23:59 UTC, merged